# Generated by Django 4.2 on 2023-04-25 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('personalWeb', models.CharField(blank=True, default='', max_length=200)),
                ('labPosition', models.CharField(blank='', choices=[('PI', 'PI'), ('PH', 'Graduate student, PhD'), ('MS', 'Graduate student, MS'), ('UG', 'Undergraduate intern'), ('VS', 'Visiting scholar'), ('PD', 'Postdoctoral scholar'), ('CO', 'Collaborator')], max_length=200)),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('shortBio', models.TextField()),
            ],
            options={
                'ordering': ['labPosition'],
            },
        ),
    ]
